export default {
appLogo: require('./images/logo.png'),
appLogo1: require('./images/logo.png'),
bag: require('./images/bag.png'),
buttonNext: require('./images/buttonNext.png'),
Mobile: require('./images/Mobile.png'),
// phonLogoapp: require('./images/Mobile.png'),
phonLogoapp: require('./images/logo.png'),
dpuser: require('./images/dpuser.png'),
Editpen: require('./images/Editpen.png'),
cooment: require('./images/cooment.png'),
Toys: require('./images/Toys.png'),
sp1: require('./images/sp1.png'),
eoditphots: require('./images/eoditphots.png'),
age: require('./images/age.png'),
Calls: require('./images/Calls.png'),
hide: require('./images/hide.png'),
profileChildName: require('./images/profileChildName.png'),
messtrcker: require('./images/messtrcker.png'),
moji: require('./images/moji.png'),
Frame: require('./images/Frame.png'),
family: require('./images/family.png'),
NotificationIcon: require('./images/NotificationIcon.png'),
Song: require('./images/Song.png'),
Parent: require('./images/Parent.png'),
tv: require('./images/tv.png'),
mess: require('./images/mess.png'),
grap: require('./images/grap.png'),
Activity: require('./images/Activity.png'),
voice: require('./images/voice.png'),
School: require('./images/School.png'),
search1: require('./images/search1.png'),
Library: require('./images/Library.png'),
Phone1: require('./images/Phone1.png'),
Ellipse: require('./images/Ellipse.png'),
helpPrva: require('./images/helpPrva.png'),
IconRed: require('./images/IconRed.png'),
Location: require('./images/Location.png'),
voies: require('./images/voies.png'),
profiel: require('./images/profiel.png'),
rightaArrow: require('./images/rightaArrow.png'),
earing: require('./images/earing.png'),
Addressicone: require('./images/Addressicone.png'),
edit1: require('./images/edit1.png'),
sp2: require('./images/sp2.png'),
Closed: require('./images/Closed.png'),
sp3: require('./images/sp3.png'),
Next: require('./images/Next.png'),
Calblack: require('./images/Calblack.png'),
icons: require('./images/icons.png'),
Positive: require('./images/Positive.png'),
Conservative: require('./images/Conservative.png'),
Vector: require('./images/Vector.png'),
Growth: require('./images/Growth.png'),
Notification: require('./images/Notification.png'),
Unknown: require('./images/Unknown.png'),
MessageBlack: require('./images/MessageBlack.png'),
trck: require('./images/trck.png'),
Dots: require('./images/Dots.png'),
arrowqdown: require('./images/arrowqdown.png'),
cars: require('./images/cars.png'),
more_vert: require('./images/more_vert.png'),
Rectangle: require('./images/Rectangle.png'),
tracking: require('./images/tracking.png'),

black: require('./images/black.png'),
location1: require('./images/location1.png'),
caricon: require('./images/caricon.jpg'),
// group: require('./images/goup2.png'),
group: require('./images/group.png'),
 right: require('./images/arrowRight.png'),
Icon: require('./images/Icon.png'),
apple: require('./images/apple.png'),
google: require('./images/google.png'),
Mesonmorpah: require('./images/Mesonmorpah.png'),
MohronFag: require('./images/MohronFag.png'),
prfile: require('./images/prfile.png'),
pushup: require('./images/pushup.png'),
running: require('./images/running.png'),
back: require('./images/back.png'),
cycling: require('./images/cycling.png'),
arrowDown: require('./images/arrowDown.png'),
logout: require('./images/logout.png'),
Filter: require('./images/Filter.png'),
dounArroww: require('./images/dounArroww.png'),
aboutus: require('./images/aboutus.png'),
BackLeft: require('./images/BackLeft.png'),
OrderPlaced: require('./images/OrderPlaced.png'),
userLogo: require('./images/userLogo.png'),
deliver: require('./images/Deliver.png'),




}; 